title: Tinder for pets
author: Team Grilled Chicken

description: >
  This is Tinder, but for pets! Shelters are able to upload the pets that they have, and people looking are able to scroll through their pets to look at what they want to adpot! 

theme: minima